### ISSUE TITLE
could not install it using brew?

### ISSUE THREAD

**Issue by CaiXunchao** [serhhatsari/askgpt#23]
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/serhhatsari/homebrew-tools/

**Comment by serhhatsari** [comment]
It should be fixed now. Can you try to install again? @CaiXunchao

**Comment by CaiXunchao** [comment]
> It should be fixed now. Can you try to install again? @CaiXunchao

Great! It works. Thank for your help.

**Comment by serhhatsari** [comment]
Closing the issue. Thank you for your feedback
